//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    
    using System;
    using System.Web;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class galery
    {
        public int ImageId { get; set; }
        public string ImageSize { get; set; }
        public string FileName { get; set; }
        public byte[] ImageData { get; set; }
        [Required(ErrorMessage = "please sekect file")]
        public HttpStyleUriParser File { get; set; }
    }
}
