//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    
    public partial class Image
    {
        public int ImageId { get; set; }
        public int Imagesize { get; set; }
        public string FileName { get; set; }
        public byte[] ImageData { get; set; }
         [Required(ErrorMessage = "Please select file")]
        public HttpPostedFileBase File { get; set; }
         

    }
}
