//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public Nullable<int> id_ { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    }
}
