//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class worksuggests
    {
        public int fileID { get; set; }
        public string fileName { get; set; }
        public string content { get; set; }
        public System.DateTime filedate { get; set; }
    }
}
